services:
  - type: web
    name: md2pdf
    runtime: docker
    dockerfilePath: ./apps/web/Dockerfile
    dockerContext: .
    plan: starter
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
